In [134]:
import os
import re
import pandas as pd

# Data Input

### getting list of all the \*.txt input files
saving the names of all the input data text files as a list

In [135]:
data_file_list = list()
data_dir = "./Dataset/ForLiwcFile/"
for file in os.listdir(data_dir):
    if file.endswith(".txt"):
        data_file_list.append(file)
# print(len(data_file_list)) #DEBUG
# print(data_file_list[0]) #DEBUG

### opening all files and reading them into a single list
open each tweet \*.txt files
read the data from the file
convert the data into a proper list with all fields in seperate columns
write the data into the master data list with all users' data

In [ ]:
data_of_all_user = list()
for file_name in data_file_list:
#     print(file_name) #DEBUG
    file_path = data_dir + file_name
    
    # lots of encoding related errors keeps coming in, 
    # that's why ignoring them when opening the files
    file = open (file_path, mode='r', errors='ignore') 
    data = file.read()
    file.close()

    # split data based on new lines
    data = data.split('\n')
    
    # data cleaning - remove lines with no input
    # need to catch exception as most files do not have empty lines
    try:
        data.remove('')
    except ValueError:
        pass     # dummy assignment
    
    # flags for Error handling
    # need this as we remove the data lines from the list
    # when there list len is != 3 after splitting by '|'
    total_valid_tweets_from_user = len(data)    
    invalid_tweet_cnt = 0
    
    # split data based on |
    # we expect to have 3 items on the list of each tweet
    # tweetid, timestamp, tweettext
    for i in range(0, total_valid_tweets_from_user):
        # as we remove the invalid tweets, it reduce
        i = i-invalid_tweet_cnt 
        data[i]=data[i].split('|')
        
        # data cleaninng - FLAGS for Error handling
        # handling the case when we dont get 3 items on the list of each tweet
        # we will remove that tweet line as it is most likely to be an error
        if len(data[i]) != 3:
            data.remove(data[i])
            invalid_tweet_cnt = invalid_tweet_cnt + 1
            total_valid_tweets_from_user = total_valid_tweets_from_user - 1

    # splitting the time filed and re-arranging them within one list per tweet
    for i in range(0, total_valid_tweets_from_user):  
#         print(data[i]) #DEBUG
        temp_timestamp_str=data[i][1] # saving timestamp in temp var
        temp_timestamp_list=re.split('[:\s]',temp_timestamp_str) # splitting timestamp based on colon(:) and white space
        data[i].remove(temp_timestamp_str) # remove the timestamp from the list of elements of each tweet
        data[i].insert(0, total_valid_tweets_from_user) # adding total tweet number from a user at the begining 
        data[i].insert(0, data_file_list[0][:-4]) # adding the userid at the begining

        # insert the elements of timestamp into the original list
        for j in range(0, len(temp_timestamp_list)):
            data[i].insert(len(data[i])-1, temp_timestamp_list[j]) 
    
    # adding all the tweets from all users in 1 single list
    for i in range(0, total_valid_tweets_from_user):
        data_of_all_user.append(data[i])

### Creating a single CSV file with all the users' data

In [136]:
output_file_path = "twitter_data.csv"

# removing old outout file if exists
if os.path.exists(output_file_path):
    os.remove(output_file_path)

# writing to csv
df_out = pd.DataFrame(data_of_all_user)
df_out.columns=['userid', 'total_tweets_by_a_user', 'tweetid', 'day_of_week', 'month', 'day', 'hour', 'minute', 'second', 'time_correction', 'year', 'tweet']
df_out.to_csv(output_file_path, sep=',', index=True, index_label='tweetcount_by_all_users')

### testing newly created single CSV file with all the users' data

In [137]:
# testing
df = pd.read_csv(output_file_path)
print("total number of tweets from all users: " + df.size)
df.head()

23411063

,tweetcount_by_all_users,userid,total_tweets_by_a_user,tweetid,day_of_week,month,day,hour,minute,second,time_correction,year,tweet
0,0,0utoftime,1533,669678001865510912,Thu,Nov,26,0,44,12,0,2015,@danielhberger or john oliver now that obama h...
1,1,0utoftime,1533,669677485240541184,Thu,Nov,26,0,42,9,0,2015,@wiz_teresa international phonetic alphabet
2,2,0utoftime,1533,669224460260651008,Tue,Nov,24,18,41,59,0,2015,@dumbnamenumbers @wiz_teresa donâ€™t you just ma...
3,3,0utoftime,1533,668476559062364160,Sun,Nov,22,17,10,6,0,2015,RT @confreaks: New Video! @RubyConf #rubyconf ...
4,4,0utoftime,1533,667735237498183680,Fri,Nov,20,16,4,21,0,2015,@wiz_teresa http://pbs.twimg.com/media/CURFqBQ...